name = "INSA hugo theme"
license = "MIT"
licenselink = "https://github.com/RCayre/insa-hugo-theme/blob/main/LICENSE"
description = "Minimal INSA Lab theme for hugo"
homepage = "https://github.com/RCayre/insa-hugo-theme/"
demosite = ""
tags = ["minimal", "dark", "blog", "sass", "multilingual"]
features = ["blog", "sass", "dark", "multilingual"]
min_version = "0.114.0"

[author]
name = "Romain Cayre"
homepage = "https://insa-toulouse.fr"
